### PR TITLE
Damage zone refactor

### PR DESCRIPTION
**Pull request by jmgoldb**
Refactored the model side of damage zones.  Redoing the layout comes next.  There's a lot of JSON changes in here, about 17.5k lines' worth.

I'm not sure if travis will pass this or will crash due to a different model.  If it fails, I might need to add in code to the tests that forces a reset of the persistent store.

### CODE REVIEW

**Comment by jmgoldb** [comment]
Looks like Travis is green!  I guess it doesn't use the existing persistent store/app data like the local iOS simulator does, which saves me a lot of headache.

Can I get a code review, please? @vokal/ios-developers

**Comment by brockboland** [comment]
yep

**Comment by jmgoldb** [comment]
Thanks

**Comment by brockboland** [comment]
LGTM

**Comment by jmgoldb** [comment]
Is anyone able to merge this?

**Comment by designatednerd** [comment]
@jmgoldb Please ping the seniors+ by handle when you need a merge - myself, @seanwolter and @chillpop have merge powers of doom.

**Comment by vokal-isaac** [comment]
Travis is building clean on a clean environment and running in a clean simulator—basically, as if it's never been used—so there won't be anything hanging around from a previous run.

**Pull request merged**
