### PR TITLE
Added YAML file for travis

### PR DESCRIPTION
**Pull request by jmgoldb**
Attempting to add travis YAML

### CODE REVIEW

**Comment by vokal-isaac** [comment]
Travis build failed.  Did you share the scheme (go to "manage schemes" and make sure the shared checkbox is checked next to the scheme you reference in the YAML file)?

**Comment by jmgoldb** [comment]
I did not.  Let me share it and repush

**Comment by jmgoldb** [comment]
Weird, when I checked out my earlier branch the scheme disappeared.  I readded it and ticked the share checkbox, let's see if this works well for travis.

**Comment by jmgoldb** [comment]
Woohoo, travis passed!

**Comment by vokal-isaac** [comment]
LGTM

**Comment by designatednerd** [comment]
:tada:

**Pull request merged**
