### PR TITLE
Added a TON of JSON files, no actual code changes

### PR DESCRIPTION
**Pull request by jmgoldb**
I made a pull request of nothing but JSON changes, could I get a quick "review" and merge, please? : )

@vokal/ios-developers

### CODE REVIEW

**Comment by brockboland** [comment]
Yep, that's JSON all right. Good to pull once Travis gives it a once-over.

**Comment by jmgoldb** [comment]
Travis is/was green, but I had to make a quick fix, and had to add two lines of code so sourceTree wouldnt freak out.

**Comment by jmgoldb** [comment]
@seanwolter  Hi Sean, can you help me out here with a merge, please?

**Comment by jmgoldb** [comment]
Thank ye kindly.

**Pull request merged**
